"use client";

import { useState } from "react";
import jsPDF from "jspdf";

export default function PrescriptionPage() {
  const [patientName, setPatientName] = useState("");
  const [medicineName, setMedicineName] = useState("");
  const [dosage, setDosage] = useState("");
  const [instructions, setInstructions] = useState("");

  const generatePDF = (event) => {
    event.preventDefault();

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("MediQueue Prescription", 20, 20);

    doc.setFontSize(12);
    doc.text("Doctor: Dr. Sarah Ahmed", 20, 35);
    doc.text(`Patient: ${patientName}`, 20, 45);
    doc.text(`Medicine: ${medicineName}`, 20, 60);
    doc.text(`Dosage: ${dosage}`, 20, 70);

    doc.text("Instructions:", 20, 85);
    doc.text(instructions, 20, 95, { maxWidth: 170 });

    doc.text("Generated by MediQueue", 20, 280);

    doc.save(`${patientName || "prescription"}-prescription.pdf`);
  };

  return (
    <main className="p-10">
      <h1 className="text-3xl font-bold">
        Create Prescription
      </h1>

      <form
        onSubmit={generatePDF}
        className="mt-6 flex flex-col gap-4"
      >
        <input
          type="text"
          placeholder="Patient Name"
          value={patientName}
          onChange={(e) => setPatientName(e.target.value)}
          className="border p-2 rounded"
        />

        <input
          type="text"
          placeholder="Medicine Name"
          value={medicineName}
          onChange={(e) => setMedicineName(e.target.value)}
          className="border p-2 rounded"
        />

        <input
          type="text"
          placeholder="Dosage"
          value={dosage}
          onChange={(e) => setDosage(e.target.value)}
          className="border p-2 rounded"
        />

        <textarea
          placeholder="Instructions"
          value={instructions}
          onChange={(e) => setInstructions(e.target.value)}
          className="border p-2 rounded"
          rows="4"
        />

        <button
          type="submit"
          className="bg-blue-600 text-white px-4 py-2 rounded"
        >
          Generate Prescription PDF
        </button>
      </form>
    </main>
  );
}