"use client";

import { Suspense, useEffect, useState } from "react";
import jsPDF from "jspdf";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebase";

function PrescriptionContent() {
  const router = useRouter();
  const searchParams = useSearchParams();

  const patientFromQueue = searchParams.get("patient") || "";
  const doctorFromQueue =
    searchParams.get("doctor") || searchParams.get("clinic") || "MediQueue Clinic";
  const specialtyFromQueue = searchParams.get("specialty") || "General Care";

  const [patientName] = useState(patientFromQueue);
  const [doctorName] = useState(doctorFromQueue);
  const [specialty] = useState(specialtyFromQueue);

  const [medicineName, setMedicineName] = useState("");
  const [dosage, setDosage] = useState("");
  const [instructions, setInstructions] = useState("");
  const [checkingAuth, setCheckingAuth] = useState(true);

  useEffect(() => {
    const unsubscribe = onAuthStateChanged(auth, (user) => {
      const role = localStorage.getItem("mediqueueRole");

      if (!user || role !== "doctor") {
        router.replace("/login");
        return;
      }

      setCheckingAuth(false);
    });

    return () => unsubscribe();
  }, [router]);

  const generatePDF = (event) => {
    event.preventDefault();

    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("MediQueue Prescription", 20, 20);

    doc.setFontSize(12);
    doc.text(`Doctor / Clinic: ${doctorName}`, 20, 35);
    doc.text(`Specialty: ${specialty}`, 20, 45);
    doc.text(`Patient: ${patientName || "Current patient"}`, 20, 55);

    doc.text(`Medicine: ${medicineName}`, 20, 75);
    doc.text(`Dosage: ${dosage}`, 20, 85);

    doc.text("Instructions:", 20, 105);
    doc.text(instructions, 20, 115, { maxWidth: 170 });

    doc.text("Generated by MediQueue", 20, 280);

    doc.save(`${patientName || "patient"}-prescription.pdf`);
  };

  if (checkingAuth) {
    return (
      <main className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center">
        <p className="text-slate-500 dark:text-slate-400">
          Checking access...
        </p>
      </main>
    );
  }

  return (
    <main className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white">
      <section className="max-w-5xl mx-auto px-4 sm:px-6 py-8 sm:py-12">
        <div>
          <p className="text-blue-600 dark:text-blue-400 font-semibold">
            Doctor Tools
          </p>

          <h1 className="text-3xl sm:text-4xl font-extrabold mt-2">
            Create Prescription
          </h1>

          <p className="text-slate-500 dark:text-slate-400 mt-2">
            Generate a downloadable prescription PDF for the current patient.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8 mt-10">
          <form
            onSubmit={generatePDF}
            className="lg:col-span-2 bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl shadow-sm p-5 sm:p-8 flex flex-col gap-5"
          >
            <div className="bg-blue-50 dark:bg-blue-500/15 border border-blue-100 dark:border-blue-400/30 rounded-2xl p-5">
              <p className="text-blue-600 dark:text-blue-300 text-sm font-semibold">
                CURRENT VISIT
              </p>

              <h2 className="text-2xl font-extrabold mt-2">
                {patientName || "Current patient"}
              </h2>

              <p className="text-slate-600 dark:text-slate-300 mt-1">
                {doctorName} • {specialty}
              </p>
            </div>

            <div>
              <label className="font-semibold text-sm">Patient Name</label>
              <input
                type="text"
                value={patientName || "Current patient"}
                readOnly
                className="mt-2 w-full border border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 dark:text-white p-3 rounded-xl outline-none cursor-not-allowed"
              />
            </div>

            <div>
              <label className="font-semibold text-sm">Doctor / Clinic</label>
              <input
                type="text"
                value={doctorName}
                readOnly
                className="mt-2 w-full border border-slate-200 dark:border-slate-700 bg-slate-100 dark:bg-slate-800 dark:text-white p-3 rounded-xl outline-none cursor-not-allowed"
              />
            </div>

            <div>
              <label className="font-semibold text-sm">Medicine Name</label>
              <input
                type="text"
                placeholder="Example: Napa Extra"
                value={medicineName}
                onChange={(e) => setMedicineName(e.target.value)}
                className="mt-2 w-full border border-slate-200 dark:border-slate-700 dark:bg-slate-800 dark:text-white p-3 rounded-xl outline-none focus:border-blue-500"
                required
              />
            </div>

            <div>
              <label className="font-semibold text-sm">Dosage</label>
              <input
                type="text"
                placeholder="Example: 1 tablet twice daily"
                value={dosage}
                onChange={(e) => setDosage(e.target.value)}
                className="mt-2 w-full border border-slate-200 dark:border-slate-700 dark:bg-slate-800 dark:text-white p-3 rounded-xl outline-none focus:border-blue-500"
                required
              />
            </div>

            <div>
              <label className="font-semibold text-sm">Instructions</label>
              <textarea
                placeholder="Example: Take after meals for 3 days."
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
                className="mt-2 w-full border border-slate-200 dark:border-slate-700 dark:bg-slate-800 dark:text-white p-3 rounded-xl outline-none focus:border-blue-500"
                rows="5"
                required
              />
            </div>

            <button
              type="submit"
              className="mt-3 bg-blue-600 text-white py-3 rounded-xl font-semibold shadow-md hover:bg-blue-700 hover:scale-[1.01] transition"
            >
              Generate Prescription PDF
            </button>
          </form>

          <aside className="bg-blue-600 text-white rounded-3xl shadow-sm p-5 sm:p-8 h-fit">
            <p className="text-blue-100 font-semibold">PDF Prescription</p>

            <h2 className="text-2xl font-bold mt-3">
              Fast digital documentation.
            </h2>

            <p className="text-blue-100 mt-4">
              Patient and clinic details are carried from the live queue, so the
              doctor only needs to enter medicine, dosage, and instructions.
            </p>

            <div className="bg-white/15 rounded-2xl p-5 mt-6">
              <p className="text-sm text-blue-100">Format</p>
              <p className="text-3xl font-bold mt-2">PDF</p>
            </div>

            <Link
              href="/doctor-queue"
              className="inline-block mt-6 bg-white text-blue-600 px-5 py-3 rounded-xl font-semibold hover:bg-blue-50 transition"
            >
              Back to Queue
            </Link>
          </aside>
        </div>
      </section>
    </main>
  );
}

export default function PrescriptionPage() {
  return (
    <Suspense
      fallback={
        <main className="min-h-screen bg-slate-50 dark:bg-slate-950 flex items-center justify-center">
          <p className="text-slate-500 dark:text-slate-400">
            Loading prescription...
          </p>
        </main>
      }
    >
      <PrescriptionContent />
    </Suspense>
  );
}