"use client";

import jsPDF from "jspdf";
import Link from "next/link";

export default function PrescriptionHistoryPage() {
  const prescriptions = [
    {
      id: 1,
      doctor: "Dr. Sarah Ahmed",
      patient: "Demo Patient",
      date: "June 20, 2026",
      medicine: "Napa Extra",
      dosage: "1 tablet twice daily",
      instructions: "Take after meals for 3 days.",
    },
    {
      id: 2,
      doctor: "Dr. Arif Hossain",
      patient: "Demo Patient",
      date: "June 18, 2026",
      medicine: "Vitamin D",
      dosage: "1 tablet daily",
      instructions: "Take in the morning after breakfast.",
    },
  ];

  const downloadPrescription = (prescription) => {
    const doc = new jsPDF();

    doc.setFontSize(22);
    doc.text("MediQueue Prescription", 20, 20);

    doc.setFontSize(12);
    doc.text(`Doctor: ${prescription.doctor}`, 20, 35);
    doc.text(`Patient: ${prescription.patient}`, 20, 45);
    doc.text(`Date: ${prescription.date}`, 20, 55);
    doc.text(`Medicine: ${prescription.medicine}`, 20, 70);
    doc.text(`Dosage: ${prescription.dosage}`, 20, 80);

    doc.text("Instructions:", 20, 95);
    doc.text(prescription.instructions, 20, 105, { maxWidth: 170 });

    doc.text("Generated by MediQueue", 20, 280);

    doc.save(`${prescription.patient}-prescription.pdf`);
  };

  return (
    <main className="min-h-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-white">
      <section className="max-w-5xl mx-auto px-6 py-12">
        <div>
          <p className="text-blue-600 dark:text-blue-400 font-semibold">
            Patient Records
          </p>

          <h1 className="text-4xl font-extrabold mt-2">
            Prescription History
          </h1>

          <p className="text-slate-500 dark:text-slate-400 mt-2">
            View and download previous prescription PDFs.
          </p>
        </div>

        <div className="grid grid-cols-1 gap-5 mt-8">
          {prescriptions.map((prescription) => (
            <div
              key={prescription.id}
              className="bg-white dark:bg-slate-900 border border-slate-100 dark:border-slate-800 rounded-3xl p-6 shadow-sm"
            >
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
                <div>
                  <h2 className="text-2xl font-bold">
                    {prescription.doctor}
                  </h2>

                  <p className="text-slate-500 dark:text-slate-400 mt-1">
                    {prescription.date} • {prescription.medicine}
                  </p>

                  <p className="text-slate-500 dark:text-slate-400 mt-1">
                    Dosage: {prescription.dosage}
                  </p>
                </div>

                <button
                  onClick={() => downloadPrescription(prescription)}
                  className="bg-blue-600 text-white px-5 py-3 rounded-xl font-semibold hover:bg-blue-700 transition"
                >
                  Download PDF
                </button>
              </div>
            </div>
          ))}
        </div>

        <Link
          href="/patient-dashboard"
          className="inline-block mt-8 border border-blue-600 text-blue-600 dark:text-blue-300 dark:border-blue-400 px-5 py-3 rounded-xl font-semibold hover:bg-blue-50 dark:hover:bg-slate-800 transition"
        >
          Back to Dashboard
        </Link>
      </section>
    </main>
  );
}
